export const languages = {
  bash: 'bash',
  c: 'c',
  clike: 'clike',
  cpp: 'cpp',
  css: 'css',
  git: 'git',
  go: 'go',
  graphql: 'graphql',
  html: 'html',
  php: 'php',
  javascript: 'javascript',
  json: 'json',
  jsx: 'jsx',
  makefile: 'makefile',
  markdown: 'markdown',
  objectivec: 'objective-c',
  ocaml: 'ocaml',
  python: 'python',
  reason: 'reason',
  sass: 'sass',
  scss: 'scss',
  sql: 'sql',
  svg: 'svg',
  typescript: 'typescript',
  xml: 'xml',
}
